#!/usr/bin/env bash
set -euo pipefail

# ── Usage ──────────────────────────────────────────────────────────────────────
# Default: installs everything next to this script (on your Mac's internal disk).
#
# External SSD: pass the SSD mount path as the first argument:
#   bash install.sh /Volumes/MySSD
#
# This will create:
#   /Volumes/MySSD/avatar-venv/    Python virtual environment (~7 GB)
#   /Volumes/MySSD/SadTalker/      SadTalker repo + model checkpoints (~3.5 GB)
#   /Volumes/MySSD/.tts/           Coqui XTTS v2 model (~2.5 GB)
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSD_ROOT="${1:-$SCRIPT_DIR}"   # first arg = SSD path, default = next to this script

VENV_DIR="$SSD_ROOT/avatar-venv"
SADTALKER_DIR="$SSD_ROOT/SadTalker"
TTS_HOME="$SSD_ROOT/.tts"      # where Coqui XTTS v2 model weights are stored

echo "==> Install target: $SSD_ROOT"
echo "    Virtual env:     $VENV_DIR"
echo "    SadTalker:       $SADTALKER_DIR"
echo "    XTTS models:     $TTS_HOME"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────────
# Python 3.11 is required — Coqui TTS does not support Python 3.12+
if ! command -v python3.11 &>/dev/null; then
  echo "ERROR: python3.11 not found. Run: brew install python@3.11"
  echo "       (Coqui TTS requires Python <3.12)"
  exit 1
fi
if ! command -v ffmpeg &>/dev/null; then
  echo "ERROR: ffmpeg not found. Run: brew install ffmpeg"
  exit 1
fi

# ── Virtual environment ────────────────────────────────────────────────────────
if [ ! -d "$VENV_DIR" ]; then
  echo "==> Creating Python 3.11 virtual environment at $VENV_DIR ..."
  python3.11 -m venv "$VENV_DIR"
else
  echo "==> Virtual environment already exists at $VENV_DIR — skipping creation."
fi

PIP="$VENV_DIR/bin/pip"
PYTHON="$VENV_DIR/bin/python"

# ── PyTorch (MPS support is included in the standard macOS wheel) ──────────────
echo "==> Installing PyTorch with MPS support (~3.5 GB) ..."
"$PIP" install torch torchvision torchaudio

# ── Service dependencies ───────────────────────────────────────────────────────
echo "==> Installing service dependencies ..."
"$PIP" install -r "$SCRIPT_DIR/requirements.txt"

# ── SadTalker ─────────────────────────────────────────────────────────────────
if [ ! -d "$SADTALKER_DIR" ]; then
  echo "==> Cloning SadTalker to $SADTALKER_DIR ..."
  git clone https://github.com/OpenTalker/SadTalker.git "$SADTALKER_DIR"
else
  echo "==> SadTalker already cloned — skipping."
fi

echo "==> Installing SadTalker dependencies ..."
"$PIP" install -r "$SADTALKER_DIR/requirements.txt"

echo "==> Downloading SadTalker model checkpoints (~3.5 GB) ..."
cd "$SADTALKER_DIR"
bash scripts/download_models.sh
cd "$SCRIPT_DIR"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "Installation complete."
echo ""
echo "NOTE: Coqui XTTS v2 model (~2.5 GB) downloads automatically on first"
echo "video request and is stored at: $TTS_HOME"
echo ""
echo "Start the service with:"
echo ""
echo "  SADTALKER_DIR=\"$SADTALKER_DIR\" \\"
echo "  XDG_DATA_HOME=\"$TTS_HOME\" \\"
echo "  LOCAL_UPLOADS_DIR=\"\$(pwd)/../api-server/uploads\" \\"
echo "  \"$PYTHON\" -m uvicorn main:app --host 0.0.0.0 --port 8001"
echo ""
echo "Or copy the start-service.sh that was created next to this script."

# ── Write a ready-to-use start script ─────────────────────────────────────────
cat > "$SCRIPT_DIR/start-service.sh" << EOF
#!/usr/bin/env bash
# Auto-generated by install.sh — edit paths here if anything moves.
set -euo pipefail

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

SADTALKER_DIR="$SADTALKER_DIR" \\
XDG_DATA_HOME="$TTS_HOME" \\
LOCAL_UPLOADS_DIR="\$SCRIPT_DIR/../api-server/uploads" \\
"$PYTHON" -m uvicorn main:app --host 0.0.0.0 --port 8001
EOF
chmod +x "$SCRIPT_DIR/start-service.sh"
echo "start-service.sh written to $SCRIPT_DIR/start-service.sh"
