#!/usr/bin/env bash
# Auto-generated by install.sh — edit paths here if anything moves.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SADTALKER_DIR="/Volumes/RecordSSD/Avatar/SadTalker" \
XDG_DATA_HOME="/Volumes/RecordSSD/Avatar/.tts" \
LOCAL_UPLOADS_DIR="$SCRIPT_DIR/../api-server/uploads" \
"/Volumes/RecordSSD/Avatar/avatar-venv/bin/python" -m uvicorn main:app --host 0.0.0.0 --port 8001
